POSITIVE:
  MINUS_DI:
    MINUS_DI14: 14
  SAR:
    SAR: 0
NEGATIVE:
  AD:
    AD: 0
  CCI:
    CCI5: 5
  CMO:
    CMO14: 14
  DEMA:
    DEMA14: 14
  KAMA:
    KAMA14: 14
  LINEARREG_ANGLE:
    LINEARREG_ANGLE5: 5
  LINEARREG_INTERCEPT:
    LINEARREG_INTERCEPT5: 5
  LINEARREG_SLOPE:
    LINEARREG_SLOPE5: 5
  LINEARREG:
    LINEARREG5: 5
  MOM:
    MOM5: 5
  OBV:
    OBV: 0
  PLUS_DI:
    PLUS_DI14: 14
  ROC:
    ROC5: 5
  RSI:
    RSI14: 14
  T3:
    T3_5: 5
  TSF:
    TSF5: 5
  TEMA:
    TEMA14: 14
  TRANGE:
    TRANGE: 0
  VAR:
    VAR5: 5
  WMA:
    WMA14: 14

